language: android
dist: trusty

android:
  components:
    - platform-tools
    - tools
    - build-tools-29.0.3
    - android-29
    - extra-google-m2repository
    - extra-android-m2repository

before_script:
  - mkdir -p ~/.android && touch ~/.android/repositories.cfg
  - curl https://gist.githubusercontent.com/liying2008/b860e3c46063faf88c3e293719f9ec58/raw/android-sdk-license.sh | sh
  - chmod +x gradlew

script: ./gradlew assembleDebug

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - $HOME/.android/build-cache
